language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
addons:
  - postgresql:
    - 9.3
    - 9.2
    - 9.1
services:
  - postgresql
  - mysql
env:
  - DJANGO=django==1.6
install:
  - pip install $DJANGO
  - python setup.py -q install
script: python src/test_project/manage.py test reversion
notifications:
  email: false
