language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
env:
  - DJANGO=django==1.6
  - DJANGO=django==1.6.1
  - DJANGO=django==1.6.2
  - DJANGO=django==1.6.3
  - DJANGO=django==1.6.4
  - DJANGO=django==1.6.5
  - DJANGO=django==1.7
matrix:
  exclude:
    - python: 2.6
      env: DJANGO=django==1.7
  fast_finish: true
install:
  - travis_retry pip install $DJANGO
  - python setup.py -q install
script: python src/test_project/manage.py test reversion
notifications:
  email: false
