language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
env:
  matrix:
    - TOX_ENV=py27-django-18-postgres
    - TOX_ENV=py27-django-18-mysql
    - TOX_ENV=py27-django-18-sqlite
    - TOX_ENV=py27-django-19-postgres
    - TOX_ENV=py27-django-19-mysql
    - TOX_ENV=py27-django-19-sqlite
    - TOX_ENV=py27-django-110-postgres
    - TOX_ENV=py27-django-110-mysql
    - TOX_ENV=py27-django-110-sqlite
    - TOX_ENV=py34-django-18-postgres
    - TOX_ENV=py34-django-18-mysql
    - TOX_ENV=py34-django-18-sqlite
    - TOX_ENV=py34-django-19-postgres
    - TOX_ENV=py34-django-19-mysql
    - TOX_ENV=py34-django-19-sqlite
    - TOX_ENV=py34-django-110-postgres
    - TOX_ENV=py34-django-110-mysql
    - TOX_ENV=py34-django-110-sqlite
    - TOX_ENV=py35-django-18-postgres
    - TOX_ENV=py35-django-18-mysql
    - TOX_ENV=py35-django-18-sqlite
    - TOX_ENV=py35-django-19-postgres
    - TOX_ENV=py35-django-19-mysql
    - TOX_ENV=py35-django-19-sqlite
    - TOX_ENV=py35-django-110-postgres
    - TOX_ENV=py35-django-110-mysql
    - TOX_ENV=py35-django-110-sqlite
  global:
    - PYTHONWARNINGS=default,ignore::PendingDeprecationWarning,ignore::ResourceWarning
    - DJANGO_DATABASE_USER_POSTGRES=postgres
    - DJANGO_DATABASE_USER_MYSQL=travis
matrix:
  fast_finish: true
services:
  - postgresql
  - mysql
install:
  - pip install tox
before_script:
  - mysql -e 'create database test_project'
  - psql -c 'create database test_project;' -U postgres;
script: tox
notifications:
  email: false
