language: python
python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4
env:
  - DJANGO=django==1.7.7
  - DJANGO=django==1.8
matrix:
  fast_finish: true
install:
  - travis_retry pip install $DJANGO
  - pip install -e .
script: python src/tests/runtests.py
notifications:
  email: false
