language: python
sudo: false
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
cache:
  directories:
    - $HOME/.cache/pip
env:
  - DJANGO=django==1.6.11
  - DJANGO=django==1.7.7
  - DJANGO=django==1.8.1
matrix:
  exclude:
    - python: 2.6
      env: DJANGO=django==1.7.7
    - python: 2.6
      env: DJANGO=django==1.8.1
  fast_finish: true
install:
  - travis_retry pip install $DJANGO
  - pip install -e .[test,diff]
script: coverage run src/tests/manage.py test src/tests/test_reversion/
after_script: coverage report
notifications:
  email: false
