language: python
python:
    - 3.5
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
env:
  matrix:
    - TOXENV=py27-django-18-postgres
    - TOXENV=py27-django-18-mysql
    - TOXENV=py27-django-18-sqlite
    - TOXENV=py27-django-19-postgres
    - TOXENV=py27-django-19-mysql
    - TOXENV=py27-django-19-sqlite
    - TOXENV=py27-django-110-postgres
    - TOXENV=py27-django-110-mysql
    - TOXENV=py27-django-110-sqlite
    - TOXENV=py34-django-18-postgres
    - TOXENV=py34-django-18-mysql
    - TOXENV=py34-django-18-sqlite
    - TOXENV=py34-django-19-postgres
    - TOXENV=py34-django-19-mysql
    - TOXENV=py34-django-19-sqlite
    - TOXENV=py34-django-110-postgres
    - TOXENV=py34-django-110-mysql
    - TOXENV=py34-django-110-sqlite
    - TOXENV=py35-django-18-postgres
    - TOXENV=py35-django-18-mysql
    - TOXENV=py35-django-18-sqlite
    - TOXENV=py35-django-19-postgres
    - TOXENV=py35-django-19-mysql
    - TOXENV=py35-django-19-sqlite
    - TOXENV=py35-django-110-postgres
    - TOXENV=py35-django-110-mysql
    - TOXENV=py35-django-110-sqlite
    - TOXENV=flake8
    - TOXENV=docs
  global:
    - PYTHONWARNINGS=default,ignore::PendingDeprecationWarning,ignore::ResourceWarning
    - DJANGO_DATABASE_USER_POSTGRES=postgres
    - DJANGO_DATABASE_USER_MYSQL=travis
matrix:
  fast_finish: true
services:
  - postgresql
  - mysql
install:
  - pip install 'tox>=2.3.1'
before_script:
  - mysql -e 'create database test_project'
  - psql -c 'create database test_project;' -U postgres;
script: tox
notifications:
  email: false
